<?php

namespace App\Models;

use App\Models\TeachersValuesTable as Teachers;
use App\Models\StudentsValuesTable as Students;

use Bitrix\Main\Localization\Loc,
    Bitrix\Main\ORM\Data\DataManager,
    Bitrix\Main\ORM\Fields\IntegerField,
    Bitrix\Main\ORM\Fields\StringField,
    Bitrix\Main\ORM\Fields\Validators\LengthValidator,
    Bitrix\Main\ORM\Fields\Validators\RegExpValidator,
    Bitrix\Main\ORM\Fields\Relations\Reference,
    Bitrix\Main\ORM\Fields\Relations\OneToMany,
    Bitrix\Main\ORM\Fields\Relations\ManyToMany,
	Bitrix\Main\ORM\Fields\FloatField,
    Bitrix\Main\Entity\Query\Join;

/**
 * Class ClassroomsValuesTable
 *
 * @package Models
 **/
class ClassroomsValuesTable extends AbstractIblockPropertyValuesTable
{
    public const IBLOCK_ID = 20;

    /**
     * Returns entity map definition.
     *
     * @return array
     */
    public static function getMap(): array
    {
        $map = [
            'Teacher' => new Reference(  
                'Teacher', 
                Teachers::class, 
                Join::on('this.ID_TEACHER','ref.IBLOCK_ELEMENT_ID')
            )
            ->configureJoinType('inner'),
            
            (new ManyToMany('STUDENT', Students::class))
            ->configureTableName('schedule')
            ->configureLocalPrimary('IBLOCK_ELEMENT_ID', 'classroom_id')
            ->configureLocalReference('ROOMS')
            ->configureRemotePrimary('IBLOCK_ELEMENT_ID', 'student_id')
            ->configureRemoteReference('STUDENT'),

        ];

        return parent::getMap() + $map; // TODO: Change the autogenerated stub

    }
}