<?php

namespace App\Models;

use App\Models\TeachersValuesTable as Teachers;
use App\Models\ClassroomsValuesTable as Rooms;
use App\Models\ScheduleTable as Schedule;

use Bitrix\Main\Localization\Loc,
    Bitrix\Main\ORM\Data\DataManager,
    Bitrix\Main\ORM\Fields\IntegerField,
    Bitrix\Main\ORM\Fields\StringField,
    Bitrix\Main\ORM\Fields\Validators\LengthValidator,
    Bitrix\Main\ORM\Fields\Validators\RegExpValidator,
    Bitrix\Main\ORM\Fields\Relations\Reference,
    Bitrix\Main\ORM\Fields\Relations\OneToMany,
    Bitrix\Main\ORM\Fields\Relations\ManyToMany,
	Bitrix\Main\ORM\Fields\FloatField,
    Bitrix\Main\Entity\Query\Join;

/**
 * Class StudentsValuesTable
 *
 * @package Models
 **/
class StudentsValuesTable extends AbstractIblockPropertyValuesTable
{
    public const IBLOCK_ID = 19;

    /**
     * Returns entity map definition.
     *
     * @return array
     */
    public static function getMap(): array
    {
        $map = [
            (new Reference(
                'TEACHER',
                teachers::class, 
                Join::on('this.ID_TEACHER', 'ref.IBLOCK_ELEMENT_ID') 
            ))->configureJoinType('inner'),

            (new OneToMany(
                'SCHEDULE',
                Schedule::class,
                'STUDENT'
            ))->configureJoinType('inner'),  

             (new ManyToMany('ROOMS', Rooms::class))
            ->configureTableName('schedule')
            ->configureLocalPrimary('IBLOCK_ELEMENT_ID', 'student_id')
            ->configureLocalReference('STUDENT')
            ->configureRemotePrimary('IBLOCK_ELEMENT_ID', 'classroom_id')
            ->configureRemoteReference('ROOMS'),
        ];
        

        return parent::getMap() + $map; // TODO: Change the autogenerated stub

    }
}