<?php

namespace App\Models;

use App\Models\StudentsValuesTable as Students;


use Bitrix\Main\Localization\Loc,
    Bitrix\Main\ORM\Data\DataManager,
    Bitrix\Main\ORM\Fields\IntegerField,
    Bitrix\Main\ORM\Fields\StringField,
    Bitrix\Main\ORM\Fields\Validators\LengthValidator,
    Bitrix\Main\ORM\Fields\Validators\RegExpValidator,
    Bitrix\Main\ORM\Fields\Relations\Reference,
    Bitrix\Main\ORM\Fields\Relations\OneToMany,
	Bitrix\Main\ORM\Fields\FloatField,
    Bitrix\Main\Entity\Query\Join;

/**
 * Class TeachersValuesTable
 *
 * @package Models
 **/
    
class TeachersValuesTable extends AbstractIblockPropertyValuesTable
{
    const IBLOCK_ID = 18;
    
    /**
     * Returns entity map definition.
     *
     * @return array
     */
    public static function getMap(): array
    {
        $map = [
            (new OneToMany(  
                'STUDENTS', 
                Students::class, 
                'TEACHER'))
				->configureJoinType('inner')            
        ];

        return parent::getMap() + $map; // TODO: Change the autogenerated stub

    }

}